### ISSUE TITLE
where are the csv datasets?

### ISSUE THREAD

**Issue by xiaoeyu6** [bitzj2015/DRL-Networking#1]
Excuse me, i'm a freshman in mobile crowdsensing. Today, i run your code, and there is a bug which show that "No such file or directory: './0_Rewards/static_result_dnc_10.csv' " i can't find them, or there are other factors to cause it.
   And, can you show more information about this research, such as references or your idea.
Thanks very much

**Comment by bitzj2015** [comment]
Hi, to run this code, you have to create four empty directories (namely '0_Rewards','1_Actions','3_loss_pi','4_loss_v'). These directories are used to store training results, which will be save as .csv files in these directories. You could also change their names in main.py. 

Since this paper is still under review, I am sorry that I cannot provide the manuscript currently. But you can search "deep reinforcement learning" and "mobile crowdsensing game" to find some research papers.

If you have any other questions, feel free to ask me.
